### ISSUE TITLE
Question object ignores "prefix" and "suffix"

### ISSUE THREAD

**Issue by kettil** [adelsz/inquirer-fuzzy-path#12]
Hi,

I am testing the plugin and I noticed a discrepancy to the question object.

The question object ignores the keys:
- prefix 
- suffix

See the [question object from Inquirer.js](https://github.com/SBoudrias/Inquirer.js#question).

-----

Example:

```
return inquirer.prompt([
    {
      type: 'fuzzypath',
      name: 'path',
      excludePath: nodePath => nodePath.startsWith('node_modules'),
      itemType: 'any',
      rootPath: 'app',
      message: 'Select a target directory for your component:',
      default: 'components/',
      suggestOnly: false,
      depthLimit: 5,
      prefix: '-->'
    }
]);
```

The arrow `-->` should be displayed before the question `Select a target ...` instead of the question mark ...

**Comment by kettil** [comment]
I did some research, in the package.json the version 5.x.x of inquirer is given, but the current version is 6.x.x. As far as I can see there was no feature in version 5.x.x yet.

Is there anything against updating the inquirer package to version 6.x.x?

**Comment by adelsz** [comment]
I have updated inquirer version to v6.0.0 in the latest release.
Also, this package relies on `inquirer-autocomplete-prompt` for drawing screen primitives, so it is probably better to open this issue there.
