### ISSUE TITLE
Add `answers` hash to excludePath

### ISSUE THREAD

**Issue by Temoto-kun** [adelsz/inquirer-fuzzy-path#4]
This could be useful for filtering directories that are dependent on previous answers.

**Comment by adelsz** [comment]
This would be nice to have. I will be glad to merge this if someone can start a PR.

**Comment by dacodekid** [comment]
@adelsz  FYKR, I created a [pull request](https://github.com/adelsz/inquirer-fuzzy-path/pull/30).

**Comment by mritzco** [comment]
Hi,

Has this been merged? Source code still missing the changes.

Would be great to have.
