### ISSUE TITLE
suggestOnly works the opposite way

### ISSUE THREAD

**Issue by GiladShoham** [adelsz/inquirer-fuzzy-path#5]
HI,
I have tried to use the suggestOnly flag.
I would expect that if the value is true I won't be able to insert my own values, however, it works the opposite way.
I think it's a bug in https://github.com/mokkabonna/inquirer-autocomplete-prompt (but maybe it's already solved and the fuzzy-path use an old version)

**Comment by adelsz** [comment]
The `inquirer-autocomplete-prompt ` dependency has now been updated.
